# See: https://docs.haskellstack.org/en/stable/travis_ci/

sudo: true

# Caching so the next build will be fast too.
cache:
  directories:
  - ~/.stack
  - ~/.local
  - ~/.stack-work-cache
  apt: true

git:
  submodules: false

before_install:
# Install GTK
- sudo apt-get update
- sudo apt-get -y install libgtk-3-dev
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- which stack
- ~/.local/bin/stack --version
# ghc
- export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - stack setup
 - stack exec -- ghc --version

script:
 - stack --no-terminal --skip-ghc-check build
 - stack --no-terminal --skip-ghc-check sdist

matrix:
  include:
  - env: GHCVER=8.6.5 CABALVER=2.4 STACK_YAML=stack-8.6.5.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.5
  - env: GHCVER=8.4.4 CABALVER=2.4 STACK_YAML=stack-8.4.4.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
  - env: GHCVER=8.2.2 CABALVER=2.0 STACK_YAML=stack-8.2.2.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.2.2
  - env: GHCVER=8.0.2 CABALVER=1.24 STACK_YAML=stack-8.0.2.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.2
